#!/bin/sh

#
# Copyright (c) dushin.net
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of dushin.net nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY dushin.net ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL dushin.net BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

PROJECT_NAME=Lethe
PROJECT_SUFFIX=.dcproj
PROJECT_CI=${PROJECT_NAME}${PROJECT_SUFFIX}-ci
PROJECT_CO=${PROJECT_NAME}-co${PROJECT_SUFFIX}
WDIR=$(dirname $0)
JS_ROOT=${WDIR}/../javascript

if [ -e "${PROJECT_CO}" ] 
then
    ARCHIVE_FILE=${PROJECT_CO}-$(date +%Y.%m.%d-%H:%M:%S).tar.gz
    if [ -e "./archives" ]
    then
        tar zcf ./archives/${ARCHIVE_FILE} ${PROJECT_CO}
    fi

    mvdir ${PROJECT_CO}/project/thirdparty/com.broofa ${JS_ROOT}/thirdparty/com.broofa
    mvdir ${PROJECT_CO}/project/thirdparty/ats.oka.nu ${JS_ROOT}/thirdparty/ats.oka.nu
    mvdir ${PROJECT_CO}/project/safari/jsolait ${JS_ROOT}/thirdparty/jsolait
    rm -rf ${PROJECT_CO}/project/mobile/jsolait
    mvdir ${PROJECT_CO}/project/foundation ${JS_ROOT}/foundation
    mvdir ${PROJECT_CO}/project/crypto ${JS_ROOT}/crypto
    mvdir ${PROJECT_CO}/project/lethe ${JS_ROOT}/lethe

    mvdir ${PROJECT_CO} ${PROJECT_CI}
    
    echo "OK!! "
    echo "OK!! You may now submit your work in ${PROJECT_CI} to subversion"
    echo "OK!! "
else
    echo "ERROR!! "
    echo "ERROR!! You have not checked out ${PROJECT_NAME}!  Try running co-project first."
    echo "ERROR!! "
    exit 1
fi

