#!/bin/sh

PROJECT_NAME=Lethe
PROJECT_SUFFIX=.dcproj
PROJECT_CI=${PROJECT_NAME}${PROJECT_SUFFIX}-ci
PROJECT_CO=${PROJECT_NAME}-co${PROJECT_SUFFIX}

if [ -e "${PROJECT_CO}" ] 
then
    mv ${PROJECT_CO} archives/${PROJECT_CI}
    pushd archives
        ARCHIVE_FILE=${PROJECT_CI}-$(date +%Y.%m.%d-%H:%M:%S).tar.gz
        tar zcf ${ARCHIVE_FILE} ${PROJECT_CI}
        rm -rf ${PROJECT_CI}
    popd
    tar zxf archives/${ARCHIVE_FILE}
    
    echo "OK!! "
    echo "OK!! You may now submit your work in ${PROJECT_CI} to subversion"
    echo "OK!! "
else
    echo "ERROR!! "
    echo "ERROR!! You have not checked out ${PROJECT_NAME}!  Try running co-project first."
    echo "ERROR!! "
    exit 1
fi

