#!/bin/sh

PROJECT_NAME=Lethe
PROJECT_SUFFIX=.dcproj
PROJECT_CI=${PROJECT_NAME}${PROJECT_SUFFIX}-ci
PROJECT_CO=${PROJECT_NAME}-co${PROJECT_SUFFIX}
WDIR=$(dirname $0)
JS_ROOT=${WDIR}/../../javascript

if [ -e "${PROJECT_CO}" ] 
then
    echo "ERROR!! "
    echo "ERROR!! You must first check in or manually (re)move ${PROJECT_CO} first.  Make sure this project has no outstanding work!"
    echo "ERROR!! "
    exit 1
fi

cp -r ${PROJECT_CI} ${PROJECT_CO}
pushd ${PROJECT_CO}
    find . -type d -name .svn | xargs rm -rf
    cpdir ${JS_ROOT}/thirdparty/com.broofa ./project/thirdparty/com.broofa
    cpdir ${JS_ROOT}/thirdparty/ats.oka.nu ./project/thirdparty/ats.oka.nu
    cpdir ${JS_ROOT}/thirdparty/jsolait ./project/safari/jsolait
    cpdir ${JS_ROOT}/thirdparty/jsolait ./project/mobile/jsolait
    cpdir ${JS_ROOT}/foundation ./project/foundation
    cpdir ${JS_ROOT}/crypto ./project/crypto
    find . -type d -name .svn | xargs rm -rf
popd

echo "OK!! "
echo "OK!! You may now do your work in ${PROJECT_CO}"
echo "OK!! "
