#!/bin/sh

PROJECT_NAME=Lethe
PROJECT_SUFFIX=.dcproj
PROJECT_CI=${PROJECT_NAME}${PROJECT_SUFFIX}-ci
PROJECT_CO=${PROJECT_NAME}-co${PROJECT_SUFFIX}

if [ -e "${PROJECT_CO}" ] 
then
    echo "ERROR!! "
    echo "ERROR!! You must first check in or manually (re)move ${PROJECT_CO} first.  Make sure this project has no outstanding work!"
    echo "ERROR!! "
    exit 1
fi

cp -r ${PROJECT_CI} ${PROJECT_CO}
pushd ${PROJECT_CO}
find . -type d -name .svn | xargs rm -rf
popd

echo "OK!! "
echo "OK!! You may now do your work in ${PROJECT_CO}"
echo "OK!! "
