/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}


function setIdentityName(event)
{
    var name = prompt("Enter your name:");
    if (name !== null) {
        var datasource = dashcode.getDataSource("lethe");
        datasource.setValueForKeyPath(name, "content.identity.name");
    }
}


function addChannel(event)
{
    var datasource = dashcode.getDataSource("lethe");
    var channelName = prompt("Enter channel name:");
    if (channelName !== null) {
        var channels = datasource.valueForKeyPath("content.channels");
        var channel = {name: channelName, peers: []};
        channels.addObject(channel);
    }
}


function switchToPeersView(event)
{
    var layout = document.getElementById("ChannelStackLayout").object;
    layout.setCurrentView("PeersView");
}


function switchToMessagesView(event)
{
    var layout = document.getElementById("ChannelStackLayout").object;
    layout.setCurrentView("MessagesView");
}


function removeChannel(event)
{
    // Insert Code Here
}


messagesToText = Class.create(
    DC.ValueTransformer,
    {
        transformedValue: function(value){
            var i;
            var s = "";
            for (i = 0;  i < value.length; ++i) {
                s += value[i].message + '\n';
            }
            return s;
        }
    }
);

