/*jsl:import DashcodePart.js*/

/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */

// Note: Properties and methods beginning with underbar ("_") are considered private and subject to change in future Dashcode releases.

/**   
 *  @declare DC.ActivityIndicator
 *  @extends DC.DashcodePart
 *  
 */

DC.ActivityIndicator= Class.create(DC.DashcodePart, {

    exposedBindings: ["animating"],
    
    partSetup: function(spec)
    {
    	var element = this.viewElement();
    
        // set the animation CSS properties
        element.style.webkitAnimationName = 'none';
        element.style.webkitAnimationDuration = "1s";
        element.style.webkitAnimationIterationCount = "infinite";
        element.style.webkitAnimationTimingFunction = "linear";
        
        if (!dashcode.inDesign) {
            this.startAnimation();
        }
    },
    
    setAnimating: function(animating) 
    {
        this.viewElement().style.webkitAnimationName = (animating ? 'dashcode-activity-indicator' : 'none');
    },
    
    animating: function()
    {
        return (this.viewElement().style.webkitAnimationName != 'none');
    },
    
    startAnimation: function() {
        this.setAnimating(true);
    },

    stopAnimation: function() {
        this.setAnimating(false);
    }
    
});


