/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "AddChannelButton": { "initialHeight": 20, "initialWidth": 20, "leftImageWidth": 5, "onclick": "addChannel", "rightImageWidth": 5, "text": "+", "view": "DC.PushButton" },
    "button1": { "initialHeight": 23, "initialWidth": 61, "leftImageWidth": 5, "onclick": "setIdentityName", "rightImageWidth": 5, "text": "Modify...", "view": "DC.PushButton" },
    "button2": { "initialHeight": 23, "initialWidth": 81, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Generate...", "view": "DC.PushButton" },
    "ChannelLabel": { "text": "Channels", "view": "DC.Text" },
    "ChannelList": { "dataArray": ["Item 1", "Item 2", "Item 3"], "labelElementId": "rowLabel", "listStyle": "List.DESKTOP_LIST", "propertyValues": { "dataArrayBinding": { "keypath": "lethe.content.channels" } }, "sampleRows": 3, "selectionEnabled": true, "useDataSource": true, "view": "DC.List" },
    "ChannelStackLayout": { "propertyValues": { "visibleBinding": { "keypath": "ChannelList.hasSelection" } }, "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "flip" }, { "direction": "left-right", "duration": "", "timing": "ease-in-out", "type": "flip" }], "view": "DC.StackLayout" },
    "GenerateKeyIndicator": { "view": "DC.ActivityIndicator" },
    "input": { "propertyValues": { "checkedBinding": { "keypath": "*.encryptTo" } }, "view": "DC.ToggleButton" },
    "input1": { "propertyValues": { "checkedBinding": { "keypath": "lethe.content.identity.signMessages" } }, "view": "DC.ToggleButton" },
    "MessagesLabel": { "text": "Messages", "view": "DC.Text" },
    "MessagesTextArea": { "propertyValues": { "valueBinding": { "keypath": "ChannelList.selection.messages", "transformer": "messagesToText" } }, "view": "DC.TextField" },
    "PeerFingerprintLabel": { "propertyValues": { "textBinding": { "keypath": "*.publicKey" } }, "text": "fingerprint", "view": "DC.Text" },
    "PeerNameLabel": { "propertyValues": { "textBinding": { "keypath": "*.name" } }, "text": "name", "view": "DC.Text" },
    "PeersLabel": { "text": "Peers", "view": "DC.Text" },
    "PeersList": { "allowsEmptySelection": true, "dataArray": ["Item 1", "Item 2", "Item 3"], "labelElementId": "PeerNameLabel", "listStyle": "List.DESKTOP_LIST", "propertyValues": { "dataArrayBinding": { "keypath": "ChannelList.selection.peers" } }, "sampleRows": 3, "useDataSource": true, "view": "DC.List" },
    "RemoveChannelButton": { "initialHeight": 20, "initialWidth": 20, "leftImageWidth": 5, "onclick": "removeChannel", "propertyValues": { "enabledBinding": { "keypath": "ChannelList.hasSelection" } }, "rightImageWidth": 5, "text": "-", "view": "DC.PushButton" },
    "rowLabel": { "propertyValues": { "textBinding": { "keypath": "*.name" } }, "text": "Item", "view": "DC.Text" },
    "SendMessageButton": { "initialHeight": 21, "initialWidth": 71, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Send", "view": "DC.PushButton" },
    "splitLayout": { "flexibleViewIndex": 1, "initialSize": 738, "initialSplitterSize": 8, "isVertical": true, "splitterPosition": 159, "view": "DC.SplitLayout" },
    "SwitchToMessagesViewButton": { "initialHeight": 22, "initialWidth": 95, "leftImageWidth": 5, "onclick": "switchToMessagesView", "rightImageWidth": 5, "text": "Messages...", "view": "DC.PushButton" },
    "SwitchToPeersViewButton": { "initialHeight": 21, "initialWidth": 64, "leftImageWidth": 5, "onclick": "switchToPeersView", "rightImageWidth": 5, "text": "Peers...", "view": "DC.PushButton" },
    "text": { "text": "Lethe Messenger", "view": "DC.Text" },
    "text1": { "text": "Name:", "view": "DC.Text" },
    "text2": { "propertyValues": { "textBinding": { "keypath": "lethe.content.identity.name" } }, "text": "fdushin", "view": "DC.Text" },
    "text3": { "text": "Fingerprint:", "view": "DC.Text" },
    "text4": { "propertyValues": { "textBinding": { "keypath": "lethe.content.identity.publicKey" } }, "text": "jsbdhgksu89347hkjflkjfdg==", "view": "DC.Text" },
    "ViewPeersButton1": { "initialHeight": 24, "initialWidth": 77, "leftImageWidth": 12, "rightImageWidth": 12, "text": "Peers...", "view": "DC.PushButton" }
};






